# Header
menu:
  主页: /
  所有文章: /archives
  # 随笔: /tags/随笔

# SubNav
subnav:
  github: "https://github.com/jqs7"
  weibo: "http://weibo.com/207330777"
  rss: "/atom.xml"
  #zhihu: "#"
  #douban: "#"
  #mail: "7@mr-se7en.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: false

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: 'UA-60229050-1'
favicon: /favicon.ico

#你的头像url
avatar: "http://cn.gravatar.com/avatar/03136339c6bc7a9585541957afcac693?s=234"
#是否开启分享
share: false
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
#duoshuo: emo7
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  iiMX: http://iimx.net/
  Mr·Lin: http://mrlin.net/
  Moonlib: http://moonlib.com/
  枫城: http://kevinsfork.info/
  李云滨: https://liyunbin.com/
  电子仓鼠: http://cangshu.me/
  科斯基摩: http://coskimo.com/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 诶？纳尼？┃電柱┃| ω・´) 这是关于一个精神分裂症患者的故事 (=ﾟωﾟ)=
